eight_points_guzzle:
  clients:
    slack:
      base_url: https://slack.com/api/

      options:
        timeout: 30
        http_errors: true
        headers:
          Accept: "application/x-www-form-urlencoded"
#          Accept: "application/json"
          Authorization: 'Bearer %env(SLACK_ACCESS_TOKEN)%'
        query:
          token: '%env(SLACK_ACCESS_TOKEN)%'
          channel: '%env(SLACK_CHANNEL)%'